;; General settings
(load "~/.emacs.d/general.el")

;; Mode specific settings
(load "~/.emacs.d/elisp.el")
;(load "~/.emacs.d/haskell.el")
(load "~/.emacs.d/python.el")
(load "~/.emacs.d/ruby.el")
(load "~/.emacs.d/perl.el")
(load "~/.emacs.d/sql.el")
;(load "~/.emacs.d/html.el")
(load "~/.emacs.d/postgresql.el")
(load "~/.emacs.d/conf.el")
(load "~/.emacs.d/organizing.el")
(load "~/.emacs.d/shell.el")
(load "~/.emacs.d/javascript.el")
(load "~/.emacs.d/java.el")
(load "~/.emacs.d/yaml.el")
(load "~/.emacs.d/markdown.el")
(load "~/.emacs.d/dockerfile.el")
